FROM yoelfme/nginx-1.13.0_node-6

MAINTAINER "Yoel Monzon" <yoelfme@hotmail.com>

# Ember port
EXPOSE 4200

# Install Ember CLI and Bower
RUN npm install -g ember-cli@2.11.0 
RUN npm install -g bower
